# Amazon Review Optimizer Configuration

# Model Configuration
models:
  lightweight:
    name: "gpt-3.5-turbo"
    cost_per_1k_tokens: 0.0015
    max_tokens: 150
  
  advanced:
    name: "gpt-4"
    cost_per_1k_tokens: 0.03
    max_tokens: 200

# Routing Configuration
routing:
  complexity_threshold: 0.6
  cache_enabled: true
  cache_similarity_threshold: 0.8

# Processing Configuration
processing:
  batch_size: 10
  delay_between_requests: 0.1
  max_retries: 3

# Data Configuration
datasets:
  amazon_reviews:
    categories: ["Electronics", "Books", "Home_and_Garden"]
    max_reviews_per_category: 2000
    min_review_length: 20

# Week Targets
week_targets:
  week1:
    total_reviews: 1000
    cost_reduction_target: 0.91
    cache_hit_rate_target: 0.82
  
  week2:
    total_reviews: 5000
    cost_reduction_target: 0.93
    additional_features: ["batch_processing", "quality_assurance"]
  
  week3:
    total_reviews: 10000
    competitive_analysis: true
    statistical_validation: true
  
  week4:
    infrastructure_focus: true
    gpu_optimization: true
    target_reduction: 0.997
